# Generated by Django 5.2.3 on 2025-07-13 15:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='latest_access',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('context', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('enc_data', models.BinaryField()),
                ('enc_iv', models.BinaryField()),
                ('enc_alg', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='rest_api.profile')),
            ],
            options={
                'verbose_name_plural': 'Identities',
                'unique_together': {('user', 'context', 'description')},
            },
        ),
    ]
