# Generated by Django 5.2.3 on 2025-07-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_profile_creation_date_profile_latest_access_identity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='enc_iv',
            new_name='salt',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='enc_alg',
        ),
        migrations.AddField(
            model_name='identity',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
