# Generated by Django 5.2.3 on 2025-08-15 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_rename_enc_iv_identity_salt_remove_identity_enc_alg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approved'), ('DC', 'Declined')], db_index=True, default='PD', max_length=2)),
                ('reason', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('challenge', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation', models.JSONField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_approved', to='rest_api.profile')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rest_api.identity')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='rest_api.profile')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='rest_api.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['holder', 'status'], name='rest_api_re_holder__fceacf_idx'), models.Index(fields=['requestor', 'created_at'], name='rest_api_re_request_0c0cae_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PD')), fields=('requestor', 'context', 'status'), name='unique_pending_request_per_requestor_context')],
            },
        ),
    ]
