# Generated by Django 5.2.3 on 2025-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='payload_algo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payload_enc',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='payload_salt',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='request_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
