# Generated by Django 5.2.3 on 2025-08-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_request_payload_algo_request_payload_enc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='payload_enc',
            new_name='encrypted_key',
        ),
        migrations.RemoveField(
            model_name='request',
            name='payload_algo',
        ),
        migrations.RemoveField(
            model_name='request',
            name='payload_salt',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_key',
        ),
        migrations.AddField(
            model_name='request',
            name='key_did',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
