# Generated by Django 5.2.3 on 2025-08-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_rename_payload_enc_request_encrypted_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='encrypted_key',
        ),
        migrations.RemoveField(
            model_name='request',
            name='key_did',
        ),
    ]
