# Generated by Django 5.2.3 on 2025-08-21 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_remove_request_encrypted_key_remove_request_key_did'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_data', models.BinaryField()),
                ('salt', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_data', to='rest_api.request')),
            ],
            options={
                'verbose_name': 'Shared Encrypted Data',
                'verbose_name_plural': 'Shared Encrypted Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
