# Generated by Django 5.2.3 on 2025-08-22 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_shareddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddata',
            name='salt',
        ),
        migrations.AddField(
            model_name='request',
            name='requestor_pubkey',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareddata',
            name='enc_key',
            field=models.TextField(default=datetime.datetime(2025, 8, 22, 8, 37, 37, 652737, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
