# Generated by Django 5.2.3 on 2025-08-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_remove_shareddata_salt_request_requestor_pubkey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareddata',
            old_name='enc_key',
            new_name='encKey_jwe',
        ),
    ]
