# Generated by Django 5.2.3 on 2025-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_rename_enc_key_shareddata_enckey_jwe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddata',
            name='encKey_jwe',
        ),
        migrations.AddField(
            model_name='shareddata',
            name='encKey_wrapped',
            field=models.BinaryField(default=b'', null=True),
        ),
        migrations.AddField(
            model_name='shareddata',
            name='wrap_salt',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
