# Generated by Django 5.2.3 on 2025-08-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0011_remove_shareddata_enckey_jwe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requestor_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
