# Generated by Django 5.2.3 on 2025-08-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_request_requestor_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareddata',
            name='encKey_wrapped',
            field=models.BinaryField(),
        ),
    ]
