# Generated by Django 5.2.3 on 2025-09-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_alter_shareddata_enckey_wrapped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='requestor_pubkey',
        ),
    ]
